post:
  description: |
    Creates a new match. This will ask bancho to create a new multiplayer channel
    and return the channel details for later use.
  operationId: createMatch

  requestBody:
    content:
      application/json:
        schema:
          properties:
            name:
              type: string
          required:
            - name
          type: object

  responses:
    201:
      content:
        application/json:
          schema:
            properties:
              avatarUrl:
                example: https://a.ppy.sh/3909293?1555203556.jpeg
                type: string
              gameUserId:
                example: 3909293
                type: integer
              name:
                example: DemonWaves
                type: string
            type: object
      description: New match created and channel opened on bancho.
    400:
      content:
        application/json:
          schema:
            properties:
              instance:
                example: /api/v1/matches
                type: string
              status:
                example: 400
                type: integer
              title:
                example: Bad Request
                type: string
              detail:
                example: Input validation failed
                type: string
              errors:
                items:
                  properties:
                    path:
                      example: /body/name
                      type: string
                    message:
                      example: name cannot be empty
                      type: string
                    errorCode:
                      example: validator.createMatchBodyValidator.name.empty
                      type: string
            type: object
      description: Missing or invalid name.
    401:
      content:
        application/json:
          schema:
            properties:
              instance:
                example: /api/v1/matches
                type: string
              status:
                example: 401
                type: integer
              title:
                example: Unauthorized
                type: string
              detail:
                example: You must be authenticated to access this resource.
                type: string
            type: object
      description: Missing or invalid authentication.

  security:
    - cookie: []
  summary: Create a new match
  tags:
    -  Matches
