FROM node:20.17.0-slim AS base-image
ARG PNPM_VERSION=9.11.0
RUN npm --global install pnpm@${PNPM_VERSION}

FROM base-image AS install-dependencies
WORKDIR /osu-tournanament-manager
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml tsconfig.json ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM install-dependencies AS install-local-packages
WORKDIR /osu-tournanament-manager/
COPY packages/tsconfig.json ./packages/
COPY packages/osu-sdk ./packages/osu-sdk/
COPY packages/prettier-config ./packages/prettier-config/
COPY packages/shared ./packages/shared/
COPY packages/api-specification ./packages/api-specification/
COPY packages/logger ./packages/logger/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM install-local-packages AS install-app
WORKDIR /osu-tournanament-manager
COPY apps/tsconfig.json ./apps/
COPY apps/server ./apps/server/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM install-app AS dev
ENV FORCE_COLOR=1
WORKDIR /osu-tournanament-manager/apps/server
ENTRYPOINT ["/usr/local/bin/pnpm"]
CMD ["run", "dev"]
