name: osu-tournament-manager

networks:
  backend:
    driver: bridge

services:
  postgres:
    container_name: postgres
    env_file:
      - ./apps/server/.env
    image: postgres:16.2
    networks:
      - backend
    ports:
      - ${DATABASE_PORT_SOURCE}:${DATABASE_PORT_TARGET}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: .
      args:
        - APP=apps/server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./apps/server/.env
    networks:
      - backend
    ports:
      - ${SERVER_PORT_SOURCE}:${SERVER_PORT_TARGET}
    restart: always
    volumes:
      - type: bind
        source: ./apps/server
        target: /osu-tournanament-manager/apps/server

version: '3.9'

volumes:
  postgres:
