name: osu-tournament-manager

networks:
  backend:
    driver: bridge

services:
  postgres:
    container_name: postgres
    env_file:
      - ./apps/server/.env
    image: postgres:16.2
    networks:
      - backend
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: .
      args:
        - APP=apps/server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./apps/server/.env
    networks:
      - backend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - type: bind
        source: ./apps/server
        target: /osu-tournanament-manager/apps/server

version: '3.9'

volumes:
  postgres:
