version: '3.9'

networks:
  backend:
    driver: bridge

volumes:
  postgres:

services:
  postgres:
    container_name: postgres
    env_file:
      - ./apps/server/.env
    image: postgres:16.2
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
