name: osu-tournament-manager

networks:
  web:
    driver: bridge

services:
  caddy:
    command:
      [
        'caddy',
        'run',
        '--watch',
        '--config',
        '/etc/caddy/Caddyfile',
        '--adapter',
        'caddyfile',
      ]
    container_name: caddy
    env_file:
      - ./.env
    image: caddy:2-alpine
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data/caddy

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile.dev
    container_name: client
    depends_on:
      server:
        condition: service_healthy
    networks:
      - web
    ports:
      - ${CLIENT_PORT_HOST}:${CLIENT_PORT_CONTAINER}
    restart: always
    volumes:
      - ./apps/client:/osu-tournament-manager/apps/client
      - ./packages/shared/dist:/osu-tournament-manager/apps/client/node_modules/@packages/shared/dist

  postgres:
    container_name: postgres
    env_file:
      - ./apps/server/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev -d osu_tournament_manager']
      interval: 1s
      timeout: 250ms
      retries: 10
    image: postgres:16.2
    networks:
      - web
    ports:
      - ${DATABASE_PORT_HOST}:${DATABASE_PORT_CONTAINER}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  package-api-specification-builder:
    container_name: package-api-specification-builder
    build:
      args:
        PACKAGE: packages/api-specification
      context: .
      dockerfile: ./docker/packages-builder/Dockerfile.dev
    restart: always
    volumes:
      - ./packages/api-specification:/osu-tournament-manager/packages/api-specification

  package-bancho-client-builder:
    container_name: package-bancho-client-builder
    build:
      args:
        PACKAGE: packages/bancho-client
      context: .
      dockerfile: ./docker/packages-builder/Dockerfile.dev
    restart: always
    volumes:
      - ./packages/bancho-client:/osu-tournament-manager/packages/bancho-client
      - ./packages/shared/dist:/osu-tournament-manager/packages/bancho-client/node_modules/@packages/shared/dist

  package-logger-builder:
    container_name: package-logger-builder
    build:
      args:
        PACKAGE: packages/logger
      context: .
      dockerfile: ./docker/packages-builder/Dockerfile.dev
    restart: always
    volumes:
      - ./packages/logger:/osu-tournament-manager/packages/logger
      - ./packages/shared/dist:/osu-tournament-manager/packages/logger/node_modules/@packages/shared/dist

  package-osu-sdk-builder:
    container_name: package-osu-sdk-builder
    build:
      args:
        PACKAGE: packages/osu-sdk
      context: .
      dockerfile: ./docker/packages-builder/Dockerfile.dev
    restart: always
    volumes:
      - ./packages/osu-sdk:/osu-tournament-manager/packages/osu-sdk
      - ./packages/shared/dist:/osu-tournament-manager/packages/osu-sdk/node_modules/@packages/shared/dist

  package-shared-builder:
    container_name: package-shared-builder
    build:
      args:
        PACKAGE: packages/shared
      context: .
      dockerfile: ./docker/packages-builder/Dockerfile.dev
    restart: always
    volumes:
      - ./packages/shared:/osu-tournament-manager/packages/shared

  redis:
    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--requirepass',
        '${REDIS_PASSWORD}',
      ]
    container_name: redis
    environment:
      - REDISCLI_AUTH=${REDIS_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 250ms
      timeout: 250ms
      retries: 10
    image: redis:7.2.5
    networks:
      - web
    ports:
      - ${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}
    restart: always
    volumes:
      - redis:/data

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile.dev
    container_name: server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      interval: 250ms
      retries: 10
      test: ['CMD', 'pnpm', 'healthcheck']
      timeout: 1s
    networks:
      - web
    ports:
      - ${SERVER_PORT_HOST}:${SERVER_PORT_CONTAINER}
    restart: always
    volumes:
      - ./apps/server:/osu-tournament-manager/apps/server
      - ./packages/api-specification/dist:/osu-tournament-manager/apps/server/node_modules/@packages/api-specification/dist
      - ./packages/bancho-client/dist:/osu-tournament-manager/apps/server/node_modules/@packages/bancho-client/dist
      - ./packages/logger/dist:/osu-tournament-manager/apps/server/node_modules/@packages/logger/dist
      - ./packages/osu-sdk/dist:/osu-tournament-manager/apps/server/node_modules/@packages/osu-sdk/dist
      - ./packages/shared/dist:/osu-tournament-manager/apps/server/node_modules/@packages/shared/dist

volumes:
  caddy:
  postgres:
  redis:
