export enum OsuBeatmapModification {
  AutoPilot = 'Relax2',
  Coop = 'KeyCoop',
  DoubleTime = 'DoubleTime',
  Easy = 'Easy',
  EightKeys = 'Key8',
  FadeIn = 'FadeIn',
  FiveKeys = 'Key5',
  Flashlight = 'Flashlight',
  FourKeys = 'Key4',
  FreeModification = 'Freemod',
  HalfTime = 'HalfTime',
  HardRock = 'HardRock',
  Hidden = 'Hidden',
  Mirror = 'Mirror',
  Nightcore = 'Nightcore',
  NineKeys = 'Key9',
  NoFail = 'NoFail',
  NoModification = 'NoMod',
  OneKey = 'Key1',
  Perfect = 'Perfect',
  Relax = 'Relax',
  SevenKeys = 'Key7',
  SixKeys = 'Key6',
  SpunOut = 'SpunOut',
  SuddenDeath = 'SuddenDeath',
  ThreeKeys = 'Key3',
  TwoKeys = 'Key2',
}

export const OsuBeatmapModificationAcronym = {
  [OsuBeatmapModification.AutoPilot]: 'AP',
  [OsuBeatmapModification.Coop]: 'CP',
  [OsuBeatmapModification.DoubleTime]: 'DT',
  [OsuBeatmapModification.Easy]: 'EZ',
  [OsuBeatmapModification.EightKeys]: '8K',
  [OsuBeatmapModification.FadeIn]: 'FI',
  [OsuBeatmapModification.FiveKeys]: '5K',
  [OsuBeatmapModification.Flashlight]: 'FL',
  [OsuBeatmapModification.FourKeys]: '4K',
  [OsuBeatmapModification.FreeModification]: 'FM',
  [OsuBeatmapModification.HalfTime]: 'HT',
  [OsuBeatmapModification.HardRock]: 'HR',
  [OsuBeatmapModification.Hidden]: 'HD',
  [OsuBeatmapModification.Mirror]: 'MR',
  [OsuBeatmapModification.Nightcore]: 'NC',
  [OsuBeatmapModification.NineKeys]: '9K',
  [OsuBeatmapModification.NoFail]: 'NF',
  [OsuBeatmapModification.NoModification]: 'NM',
  [OsuBeatmapModification.OneKey]: '1K',
  [OsuBeatmapModification.Perfect]: 'PF',
  [OsuBeatmapModification.Relax]: 'RX',
  [OsuBeatmapModification.SevenKeys]: '7K',
  [OsuBeatmapModification.SixKeys]: '6K',
  [OsuBeatmapModification.SpunOut]: 'SO',
  [OsuBeatmapModification.SuddenDeath]: 'SD',
  [OsuBeatmapModification.ThreeKeys]: '3K',
  [OsuBeatmapModification.TwoKeys]: '2K',
};

export enum OsuGameMode {
  Catch = 'catch',
  Mania = 'mania',
  Standard = 'standard',
  Taiko = 'taiko',
}
