info:
  license:
    name: GNU General Public License v3.0
    url: https://github.com/kibotrel/osu-tournament-manager/blob/main/LICENSE
  title: osu! tournament manager API
  version: 0.0.1

openapi: 3.0.0

paths:
  /public/health:
    $ref: paths/v1/public/health.openapi.yaml
  /public/login:
    $ref: paths/v1/public/login.openapi.yaml
  /public/logout:
    $ref: paths/v1/public/logout.openapi.yaml

servers:
  - url: https://{environment}.osu-tournament-manager.app/api/{version}
    variables:
      environment:
        default: dev
        enum:
          - dev
          - production
          - staging
      version:
        default: v1
        enum:
          - v1

tags:
  - name: Public
    description: |
      Publicly available ressources, no authentication required.
