info:
  license:
    name: GNU General Public License v3.0
    url: https://github.com/kibotrel/osu-tournament-manager/blob/main/LICENSE
  title: osu! tournament manager API
  version: 0.0.1

openapi: 3.0.0

paths:
  /authentication/login:
    post:
      $ref: paths/v1/authentication/login.openapi.yaml
  /authentication/logout:
    post:
      $ref: paths/v1/authentication/logout.openapi.yaml
  /matches:
    post:
      $ref: paths/v1/matches/createMatch.openapi.yaml
  /matches/{id}:
    get:
      $ref: paths/v1/matches/getMatch.openapi.yaml
  /matches/{id}/close:
    post:
      $ref: paths/v1/matches/closeMatch.openapi.yaml
  /public/health:
    get:
      $ref: paths/v1/public/health.openapi.yaml

servers:
  - url: https://{environment}.osu-tournament-manager.app/api/{version}
    variables:
      environment:
        default: dev
        enum:
          - dev
          - production
          - staging
      version:
        default: v1
        enum:
          - v1

tags:
  - name: Authentication
    description: |
      User session management.
  - name: Matches
    description: |
      Match management and related operations.
  - name: Public
    description: |
      Publicly available resources, no authentication required.

components:
  securitySchemes:
    cookie:
      type: apiKey
      in: cookie
      name: sessionId
