FROM node:22.13.0-slim AS base-image
ARG PNPM_VERSION=9.15.4
RUN npm --global install pnpm@${PNPM_VERSION}

FROM base-image AS install-dependencies
WORKDIR /osu-tournament-manager
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml tsconfig.json ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM install-dependencies AS install-local-packages
WORKDIR /osu-tournament-manager/
COPY packages/tsconfig.json ./packages/
COPY packages/prettier-config ./packages/prettier-config/
COPY packages/shared ./packages/shared/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM install-local-packages AS install-app
WORKDIR /osu-tournament-manager
COPY apps/tsconfig.json ./apps/
COPY apps/client ./apps/client/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM install-app AS dev
WORKDIR /osu-tournament-manager/apps/client
ENTRYPOINT ["/usr/local/bin/pnpm"]
CMD ["run", "dev"]
