name: Pull request checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-apps-server:
    name: Server
    needs:
      - detect-changes
      - lint-apps-server
      - unit-tests-packages-apps-server
      - type-check-apps-server

    if: ${{ needs.detect-changes.outputs.apps-server == 'true' }}

    uses: ./.github/workflows/build_artifact.yml
    with:
      path: apps/server

  build-apps-client:
    name: Client
    needs:
      - detect-changes
      - lint-apps-client
      - unit-tests-packages-apps-client
      - type-check-apps-client

    if: ${{ needs.detect-changes.outputs.apps-client == 'true' }}

    uses: ./.github/workflows/build_artifact.yml
    with:
      path: apps/client

  build-packages-api-specification:
    name: API specification
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-api-specification == 'true' }}

    uses: ./.github/workflows/build_artifact.yml
    with:
      path: packages/api-specification

  build-packages-bancho-client:
    name: Bancho client
    needs:
      - detect-changes
      - lint-packages-bancho-client
      - unit-tests-packages-bancho-client
      - type-check-packages-bancho-client

    if: ${{ needs.detect-changes.outputs.packages-bancho-client == 'true' }}

    uses: ./.github/workflows/build_artifact.yml
    with:
      path: packages/bancho-client

  build-packages-logger:
    name: Logger
    needs:
      - detect-changes
      - lint-packages-logger
      - type-check-packages-logger

    if: ${{ needs.detect-changes.outputs.packages-logger == 'true' }}

    uses: ./.github/workflows/build_artifact.yml
    with:
      path: packages/logger

  build-packages-osu-sdk:
    name: Osu SDK
    needs:
      - detect-changes
      - lint-packages-osu-sdk
      - type-check-packages-osu-sdk

    if: ${{ needs.detect-changes.outputs.packages-osu-sdk == 'true' }}

    uses: ./.github/workflows/build_artifact.yml
    with:
      path: packages/osu-sdk

  build-packages-shared:
    name: Shared package
    needs:
      - detect-changes
      - lint-packages-shared
      - unit-tests-packages-shared
      - type-check-packages-shared

    if: ${{ needs.detect-changes.outputs.packages-shared == 'true' }}

    uses: ./.github/workflows/build_artifact.yml
    with:
      path: packages/shared

  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      apps-client: ${{ steps.filter.outputs.apps-client }}
      apps-server: ${{ steps.filter.outputs.apps-server }}
      packages-api-specification: ${{ steps.filter.outputs.packages-api-specification }}
      packages-bancho-client: ${{ steps.filter.outputs.packages-bancho-client }}
      packages-logger: ${{ steps.filter.outputs.packages-logger }}
      packages-osu-sdk: ${{ steps.filter.outputs.packages-osu-sdk }}
      packages-shared: ${{ steps.filter.outputs.packages-shared }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Detect changed folders
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            apps-client:
              - apps/client/**
            apps-server:
              - apps/server/**
            packages-api-specification:
              - packages/api-specification/**
            packages-bancho-client:
              - packages/bancho-client/**
            packages-osu-sdk:
              - packages/osu-sdk/**
            packages-logger:
              - packages/logger/**
            packages-shared:
              - packages/shared/**

  lint-apps-client:
    name: Client
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.apps-client == 'true' }}

    uses: ./.github/workflows/run_lint.yml
    with:
      path: apps/client

  lint-apps-server:
    name: Server
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.apps-server == 'true' }}

    uses: ./.github/workflows/run_lint.yml
    with:
      path: apps/server

  lint-packages-bancho-client:
    name: Bancho client
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-bancho-client == 'true' }}

    uses: ./.github/workflows/run_lint.yml
    with:
      path: packages/bancho-client

  lint-packages-logger:
    name: Logger
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-logger == 'true' }}

    uses: ./.github/workflows/run_lint.yml
    with:
      path: packages/logger

  lint-packages-osu-sdk:
    name: Osu SDK
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-osu-sdk == 'true' }}

    uses: ./.github/workflows/run_lint.yml
    with:
      path: packages/osu-sdk

  lint-packages-shared:
    name: Shared package
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-shared == 'true' }}

    uses: ./.github/workflows/run_lint.yml
    with:
      path: packages/shared

  unit-tests-packages-bancho-client:
    name: Bancho client
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-bancho-client == 'true' }}

    uses: ./.github/workflows/run_unit_tests_suite.yml
    with:
      path: packages/bancho-client

  unit-tests-packages-shared:
    name: Shared package
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-shared == 'true' }}

    uses: ./.github/workflows/run_unit_tests_suite.yml
    with:
      path: packages/shared

  unit-tests-packages-apps-server:
    name: Server
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.apps-server == 'true' }}

    uses: ./.github/workflows/run_unit_tests_suite.yml
    with:
      path: apps/server

  type-check-apps-client:
    name: Client
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.apps-client == 'true' }}

    uses: ./.github/workflows/run_type_check.yml
    with:
      path: apps/client

  type-check-apps-server:
    name: Server
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.apps-server == 'true' }}

    uses: ./.github/workflows/run_type_check.yml
    with:
      path: apps/server

  type-check-packages-bancho-client:
    name: Bancho client
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-bancho-client == 'true' }}

    uses: ./.github/workflows/run_type_check.yml
    with:
      path: packages/bancho-client

  type-check-packages-logger:
    name: Logger
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-logger == 'true' }}

    uses: ./.github/workflows/run_type_check.yml
    with:
      path: packages/logger

  type-check-packages-osu-sdk:
    name: Osu SDK
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-osu-sdk == 'true' }}

    uses: ./.github/workflows/run_type_check.yml
    with:
      path: packages/osu-sdk

  type-check-packages-shared:
    name: Shared package
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-shared == 'true' }}

    uses: ./.github/workflows/run_type_check.yml
    with:
      path: packages/shared
