name: Pull request checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  detect-changes:
    name: Detect changed folders
    runs-on: ubuntu-latest

    outputs:
      apps-server: ${{ steps.filter.outputs.apps-server }}
      packages-bancho-client: ${{ steps.filter.outputs.packages-bancho-client }}
      packages-shared: ${{ steps.filter.outputs.packages-shared }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Detect changed folders
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            apps-server:
              - 'apps/server/**'
            packages-bancho-client:
              - 'packages/bancho-client/**'
            packages-shared:
              - 'packages/shared/**'

  packages-bancho-client-unit-tests:
    name: Bancho client unit tests
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-bancho-client == 'true' }}

    uses: ./.github/workflows/run_unit_tests_suite.yml
    with:
      path: 'packages/bancho-client'

  packages-shared-unit-tests:
    name: Shared package unit tests
    needs:
      - detect-changes

    if: ${{ needs.detect-changes.outputs.packages-shared == 'true' }}

    uses: ./.github/workflows/run_unit_tests_suite.yml
    with:
      path: 'packages/shared'

  packages-apps-server-unit-tests:
    name: Server unit tests
    needs:
      - detect-changes
      - packages-bancho-client-unit-tests
      - packages-shared-unit-tests

    if: ${{ needs.detect-changes.outputs.apps-server == 'true' || needs.detect-changes.outputs.packages-bancho-client == 'true' || needs.detect-changes.outputs.packages-shared == 'true' }}

    uses: ./.github/workflows/run_unit_tests_suite.yml
    with:
      path: 'apps/server'
