name: 'Pull request'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install pnpm v9.15.4
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 9.15.4

      - name: Install node v22.13.0
        uses: actions/setup-node@v4.4.0
        with:
          cache: 'pnpm'
          node-version: 22.13.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test -- run
