name: 'Pull Request Sizing'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label_pull_request:
    name: 'Set Pull Request Size Label'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: ls -lR
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
