name: Run lint

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  test-suite:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install pnpm v9.15.4
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 9.15.4

      - name: Get pnpm store path
        id: pnpm-store-path
        run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Use pnpm cache
        uses: actions/cache@v4.2.3
        with:
          path: ${{ steps.pnpm-store-path.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}


      - name: Install node v22.13.0
        uses: actions/setup-node@v4.4.0
        with:
          cache: 'pnpm'
          node-version: 22.13.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint on ${{ inputs.path }}
        run: pnpm --filter ./${{ inputs.path }} lint
